### PR TITLE
Add Release, Changelog Workflow Job and Validate PR Title Workflow Job

### PR DESCRIPTION
**Pull request by dcallao**
This PR contain the following changes:
- Adds a new manual CI job titled `generate-release` to generate both the git release and update the CHANGELOG.md
- The CI relies on the [semantic release action](https://github.com/marketplace/actions/action-for-semantic-release)
- This action is configured with 2 major plugins: [commit-analyzer](https://github.com/semantic-release/commit-analyzer) and [release-notes-generator](https://github.com/semantic-release/release-notes-generator)
- [commit-analyzer](https://github.com/semantic-release/commit-analyzer)  - This will examine the commits and look for keywords in the commit message, based on the [conventional commits convention](https://www.conventionalcommits.org/en/v1.0.0/), then update github release with the corresponding semantic change
- [release-notes-generator](https://github.com/semantic-release/release-notes-generator) - This will update the CHANGELOG.md file with the relative info about each release and changes within. 
- Example job run [here](https://github.com/dcallao/terraform-equinix-template/actions/runs/4410569133/jobs/7728166385)
- Adds a a new CI job titled `validate-pr-title` that will validate the title of the PR based on the [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#specification) keyword. This job is run on each PR types: open, edited, and synchronize.

Notes: 
- Commit message must be formatted following the [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#specification)

### CODE REVIEW

**Comment by dcallao** [comment]
@ctreatma I have added the CI jobs that we chatted about today. I will also submit a PR to update the [Equinix Terraform Modules](https://github.com/equinix-labs/equinix-labs/blob/main/terraform-modules.md) documentation, section 6.

**Comment by dcallao** [comment]
@ctreatma I have submitted this [PR](https://github.com/equinix-labs/equinix-labs/pull/103) in the Terraform Modules markdown doc to reflect the changes of this PR. Thx!

**Review by ctreatma — APPROVED** [review]
This looks good to me.  I think we should set up a running example of these workflows after merge so that we can check that the workflows work together as expected.

**Comment by dcallao** [comment]
@ctreatma This is an [example PR](https://github.com/dcallao/terraform-equinix-template/pull/14) with the new CI release and changelog generator. This is the [release generated by the PR above](https://github.com/dcallao/terraform-equinix-template/releases). This is the [changelog generated by the PR above](https://github.com/dcallao/terraform-equinix-template/blob/main/CHANGELOG.md)

**Pull request merged**
